[package]
name = "gd-client"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6.11", features = ["csr", "nightly"] }
leptos-use = "0.10.10"
stylers = "0.3.2"

[build-dependencies]
stylers = {  version = "0.3.2" }
